version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine  # Usamos uma imagem oficial e leve do Postgres
    container_name: postgres_db
    environment:
      # Essas variáveis são usadas pela imagem do Postgres para inicializar o banco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SgcPgmBH2025
      POSTGRES_DB: gerenciamento_computadores_db
    ports:
      # Mapeia a porta do Postgres para a sua máquina (ótimo para depuração com DBeaver, etc.)
      - "5442:5432"
    volumes:
      # Este volume garante que os dados do seu banco de dados sobrevivam
      - postgres-sgc-data:/var/lib/postgresql/data

  # Serviço do Backend
  backend:
    container_name: sgc-backend
    build:
      context: ./backend-gerenciamento-computadores
    ports:
      - "5170:5000"
    volumes:
      - ./backend-gerenciamento-computadores:/app
    environment:
      # A melhor prática é passar a URL de conexão como uma variável de ambiente
      DATABASE_URL: "postgresql://postgres:SgcPgmBH2025@db:5432/gerenciamento_computadores_db"
      FLASK_ENV: development
      FLASK_APP: src/main.py
    depends_on:
      # Garante que o contêiner 'db' seja iniciado ANTES do contêiner 'backend'
      - db

  # Serviço do Frontend (sem alterações)
  frontend:
    container_name: sgc-frontend
    build:
      context: ./frontend-gerenciamento-computadores
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-gerenciamento-computadores:/app
      - /app/node_modules
    depends_on:
      - backend

# Declaração do volume nomeado que será usado pelo Postgres
volumes:
  postgres-sgc-data: