apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gen-computadores
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: suppregistry.azurecr.io/frontend-gerenciamento-computadores:latest
        ports:
        - containerPort: 80